### ISSUE TITLE
Add CSS: registerProperty() support to theme 

### ISSUE THREAD

**Issue by morewings** [morewings/react-forge-ui#182]
The goal is to support color animation

```js
CSS.registerProperty({
  name: '--stop-color',
  syntax: '<color>',
  inherits: false,
  initialValue: 'blue',
});
```

```css

button {
  --stop-color: red;
  transition: --stop-color 1s;
}

button:hover {
  --stop-color: green;
}

```

https://developer.mozilla.org/en-US/docs/Web/API/CSS/registerProperty_static

https://www.w3.org/TR/css-properties-values-api-1/#supported-names

Related: https://github.com/morewings/css-vars-hook/issues/17
